---
# handlers file for celery-docker

- name: create celery-worker tmpfiles
  become: yes
  command: systemd-tmpfiles --create /etc/tmpfiles.d/celery-worker.conf

- name: reload celery-worker
  become: yes
  systemd:
    daemon_reload: yes
    name: celery-worker.service
    state: restarted
